"""
Django settings for CrazyTeseter project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import os
import pymysql
pymysql.install_as_MySQLdb()


DB_HOST = '127.0.0.1'
IP = "http://127.0.0.1:80"
# CRON_TASK_START = False
CRON_TASK_START = True

DB_PASSWORD = "******"
DB_PORT = 3306
DB_USER = 'root'
DB_NAME = "api_auto"

DEBUG = True

TIME_OUT = 10   # 发送请求的超时时间
REQUEST_SLEEP = 0.2    # 场景测试下,每一个请求的时间间隔
THREAD_MAX_WORKERS = 32     # 测试任务(全量/冒烟)运行最大线程

MAIL_HOST = "smtp.exmail.qq.com"  # SMTP服务器 (火狐)

SENDER = '****@**'
MAIL_PASS = "****"  # 授权密码或登录密码
RECEIVERS = ["****@**"]   # 默认接收

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qyxjxiu&^jp@s%z%hy%7%8z2t6z*qdpl2j*sdcn_5(6ykt7p7$'


ALLOWED_HOSTS = ["*"]

# AUTH_USER_MODEL = 'api.User'

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "api.extensions.MD.MD",
]

ROOT_URLCONF = 'CrazyTester.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + "/templates", ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CrazyTester.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 或者使用 mysql.connector.django
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        # 'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/


# 这里是服务器实际的静态文件地址，对应服务器下的目录，
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

STATIC_URL = "/static/"

# 服务器的静态文件路径
STATIC_ROOT = '/var/www/CrazyTester/static/'

# 设置上传的文件的存放路径,这个是真是路径，文件保存到服务器的时候用的
MEDIA_ROOT = os.path.join(BASE_DIR, "upload")
# 这个是虚拟路径，配合虚拟静态文件存放路径static，制造的虚拟文件路径/media，用于保护在链接中指向访问静态文件下的上传文件
MEDIA_ROOT_VIRTUAL = '/var/www/CrazyTester/upload'
# MEDIA_ROOT_VIRTUAL = r'C:\Users\Crazy_G\Desktop\temp'









