# Generated by Django 2.1.3 on 2020-03-07 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='测试报告标题')),
                ('report_id', models.CharField(max_length=100, null=True)),
                ('report', models.TextField(null=True)),
                ('tester', models.CharField(max_length=100, null=True)),
                ('c_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '测试报告',
                'db_table': 'testreport',
                'verbose_name_plural': '测试报告',
            },
            managers=[
                ('m', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TestReportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100, null=True)),
                ('api_id', models.CharField(max_length=100, null=True)),
                ('case_id', models.CharField(max_length=100, null=True)),
                ('final_ret', models.CharField(max_length=100, null=True)),
                ('case_info', models.TextField(null=True)),
                ('c_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '测试报告详情用例数据',
                'db_table': 'testreport_detail',
                'verbose_name_plural': '测试报告详情用例数据',
            },
            managers=[
                ('m', django.db.models.manager.Manager()),
            ],
        ),
    ]
